#!/bin/bash
# Called: $0 (quiesce|resume) source

##
# This matches the structure of the postgresql init script
NAME=`basename $0`
PGDATA=/var/lib/pgsql/data
# Override defaults from /etc/sysconfig/pgsql if file is present
[ -f /etc/sysconfig/pgsql/${NAME} ] && . /etc/sysconfig/pgsql/${NAME}
##

freeze () {
  su postgres -c "select pg_start_backup('system snapshot');"
}

thaw () {
  su postgres -c "select pg_stop_backup();"
}

check_ownership () {
  # The first argument is unused
  shift
  # If there are no remaining arguments, assume we are freezing a
  # filesystem that contains our data.
  test "$#" = 0 && return 0
  # Otherwise, check for the data in the remaining paths given
  # as arguments.
  test -e "$PGDATA" || return 1
  for path in "$@"
  do
    datadev=$(stat --printf '%d' "$PGDATA")
    argdev=$(stat --printf '%d' "$1")
    test "$datadev" = "$argdev" && return 0
  done
  return 1
}

check_ownership "$@" || exit 1
case "$1" in
  freeze) freeze "$2";;
  thaw) thaw "$2";;
esac
exit 0
